// Copyright (c) Tunnel Vision Laboratories, LLC. All Rights Reserved.
// Licensed under the Apache License, Version 2.0. See LICENSE in the project root for license information.

// <auto-generated />
// This code is not auto-generated but is a copy-paste from https://github.com/DotNetAnalyzers/StyleCopAnalyzers for which
// we want to ignore all issues.

namespace SonarAnalyzer.ShimLayer.CSharp
{
    using System;
    using Microsoft.CodeAnalysis.CSharp.Syntax;

    internal static class StackAllocArrayCreationExpressionSyntaxExtensions
    {
        private static readonly Func<StackAllocArrayCreationExpressionSyntax, InitializerExpressionSyntax> InitializerAccessor;
        private static readonly Func<StackAllocArrayCreationExpressionSyntax, InitializerExpressionSyntax, StackAllocArrayCreationExpressionSyntax> WithInitializerAccessor;

        static StackAllocArrayCreationExpressionSyntaxExtensions()
        {
            InitializerAccessor = LightupHelpers.CreateSyntaxPropertyAccessor<StackAllocArrayCreationExpressionSyntax, InitializerExpressionSyntax>(typeof(StackAllocArrayCreationExpressionSyntax), nameof(Initializer));
            WithInitializerAccessor = LightupHelpers.CreateSyntaxWithPropertyAccessor<StackAllocArrayCreationExpressionSyntax, InitializerExpressionSyntax>(typeof(StackAllocArrayCreationExpressionSyntax), nameof(Initializer));
        }

        public static InitializerExpressionSyntax Initializer(this StackAllocArrayCreationExpressionSyntax syntax)
        {
            return InitializerAccessor(syntax);
        }

        public static StackAllocArrayCreationExpressionSyntax WithInitializer(this StackAllocArrayCreationExpressionSyntax syntax, InitializerExpressionSyntax initializer)
        {
            return WithInitializerAccessor(syntax, initializer);
        }
    }
}
